name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: |
        npm install
        npm install --save-dev @types/node
        
    - name: Install MCP SDK
      run: npm install @modelcontextprotocol/sdk
      
    - name: Build
      run: npm run build || true
      
    - name: Run type check with --no-error-on-unmatched-pattern
      run: npx tsc --noEmit --skipLibCheck
      
    # Uncomment when tests are added
    # - name: Run tests
    #   run: npm test 